In [25]:
import pandas as pd
data=pd.read_csv("insurance_pre.csv")
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [26]:
data=pd.get_dummies(data,drop_first=True).astype(int)
data

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [55]:
#Input and Output
independent=data[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=data[['charges']]

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [63]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': ['sqrt', 'log2'],
    'n_estimators': [10, 100]
}

grid = GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1,cv=2)

grid.fit(x_train, y_train)

Fitting 2 folds for each of 8 candidates, totalling 16 fits

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=2, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [64]:
# print best parameter after tuning

re = grid.cv_results_

grid_predictions = grid.predict(x_test)

from sklearn.metrics import r2_score

r_score = r2_score(y_test, grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_))

table = pd.DataFrame.from_dict(re)

table

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,mean_test_score,std_test_score,rank_test_score
0,0.041067,0.001103,0.007560,0.000098,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.764487,0.780793,0.772640,0.008153,7
1,0.367252,0.008579,0.033251,0.000928,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.793223,0.799824,0.796524,0.003301,3
2,0.041115,0.001795,0.007603,0.000215,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.785391,0.781406,0.783399,0.001992,6
3,0.337885,0.008352,0.029235,0.001360,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.786433,0.806435,0.796434,0.010001,4
4,0.073447,0.001076,0.007409,0.000011,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.738251,0.799884,0.769068,0.030816,8
5,0.701126,0.013450,0.031548,0.002653,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.794607,0.806275,0.800441,0.005834,2
6,0.084860,0.001928,0.008177,0.000434,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.763524,0.815056,0.789290,0.025766,5
7,0.599376,0.082427,0.024780,0.003657,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.799186,0.812676,0.805931,0.006745,1

In [46]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:20
BMI:27.
Children:0
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [60]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1967.]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(