In [25]:
import pandas as pd
data=pd.read_csv("insurance_pre.csv")
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [26]:
data=pd.get_dummies(data,drop_first=True).astype(int)
data

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [29]:
#Input and Output
independent=data[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=data[['charges']]

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [44]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {
    'kernel': ['rbf','linear'],
    'C': [10,100,1000],
    'gamma': ['scale']
}

grid = GridSearchCV(SVR(),param_grid,refit=True,verbose=3,  n_jobs=-1,cv=2)

grid.fit(x_train, y_train)

Fitting 2 folds for each of 6 candidates, totalling 12 fits

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=2, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000], 'gamma': ['scale'],
                         'kernel': ['rbf', 'linear']},
             verbose=3)

In [45]:
# print best parameter after tuning

re = grid.cv_results_

grid_predictions = grid.predict(x_test)

from sklearn.metrics import r2_score

r_score = r2_score(y_test, grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_))

table = pd.DataFrame.from_dict(re)

table

The R_score value for best parameter {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}:

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,mean_test_score,std_test_score,rank_test_score
0,0.026797,0.001091,0.032344,0.004238,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.021276,-0.195812,-0.108544,0.087268,4
1,0.037735,0.005029,0.013797,0.001964,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.034259,-0.173358,-0.103808,0.069550,3
2,0.028399,0.001781,0.029981,0.001978,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.053376,-0.229053,-0.141214,0.087839,5
3,0.060423,0.003599,0.014782,0.000400,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.447999,0.262606,0.355302,0.092697,2
4,0.031058,0.001315,0.032462,0.001164,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.094481,-0.243873,-0.169177,0.074696,6
5,0.239098,0.014835,0.011921,0.003255,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.607273,0.553811,0.580542,0.026731,1

In [46]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:20
BMI:27.
Children:0
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [52]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1294.37534494]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(